// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WiseOldMan.Bot.Data;

#nullable disable

namespace WiseOldMan.Migrations.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260920111725_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WiseOldMan.Bot.Models.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("WiseOldMan.Bot.Models.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DiscordID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("WiseOldMan.Bot.Models.PlayerItem", b =>
                {
                    b.Property<int>("PlayerItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerItemID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<decimal>("PlayerID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("PlayerID1")
                        .HasColumnType("int");

                    b.HasKey("PlayerItemID");

                    b.HasIndex("ItemID");

                    b.HasIndex("PlayerID1");

                    b.ToTable("PlayerItem", (string)null);
                });

            modelBuilder.Entity("WiseOldMan.Bot.Models.PlayerSkill", b =>
                {
                    b.Property<int>("PlayerSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerSkillID"));

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<decimal>("PlayerID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("PlayerID1")
                        .HasColumnType("int");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.HasKey("PlayerSkillID");

                    b.HasIndex("PlayerID1");

                    b.HasIndex("SkillID");

                    b.ToTable("PlayerSkill", (string)null);
                });

            modelBuilder.Entity("WiseOldMan.Bot.Models.Skill", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("WiseOldMan.Bot.Models.PlayerItem", b =>
                {
                    b.HasOne("WiseOldMan.Bot.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WiseOldMan.Bot.Models.Player", "Player")
                        .WithMany("Items")
                        .HasForeignKey("PlayerID1");

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WiseOldMan.Bot.Models.PlayerSkill", b =>
                {
                    b.HasOne("WiseOldMan.Bot.Models.Player", "Player")
                        .WithMany("Skills")
                        .HasForeignKey("PlayerID1");

                    b.HasOne("WiseOldMan.Bot.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("WiseOldMan.Bot.Models.Player", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
